name:                owoify-hs
version:             1.0.0.0
github:              "deadshot465/owoify-hs"
license:             MIT
author:              "Chehui Chou"
maintainer:          "tetsuki.syu1315@gmail.com"
copyright:           "2021 Chehui Chou"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Turn any English text into nonsensical babyspeaks.
category:            Text

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/deadshot465/owoify-hs#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 1.2.4 && < 1.3
- regex == 1.1.0.0
- regex-with-pcre == 1.1.0.0
- random >= 1.2.0 && < 1.3
- HUnit >= 1.6.2.0 && < 1.7

library:
  source-dirs: src

executables:
  owoify-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - owoify-hs

tests:
  owoify-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - owoify-hs
